### ISSUE TITLE
Summary: Meets expectations

### ISSUE THREAD

**Issue by martoio** [cardoso457/prj-rev-bwfs-dasmoto#7]
Good job on the code! Your code meets the spec and is free from any major errors. Take a look at the previous issues to polish up the code and make it more professional.

In terms of improvements, I would suggest taking a look at the article about semantic HTML and trying to improve your HTML to make it more semantic (ie, meaningful). It seems like an irrelevant thing, but it's what makes your code stand out as professional.

If you are interested in learning more about some HTML/CSS best practices, check out some of the links below:
https://github.com/bendc/frontend-guidelines
http://learn.shayhowe.com/html-css/writing-your-best-code/

Good job on this project and keep up the good work!

**Comment by cardoso457** [comment]
Thanks @martoio .  I´m going to check all the points during the weekend.
Thanks a lot.
Best regards.
Rui :)

**Comment by cardoso457** [comment]
Here is attached the file correction after review.
Thanks for help.
You can review again if you want.
Best regards @martoio ,

Rui

**Comment by cardoso457** [comment]
https://github.com/cardoso457/prj-rev-bwfs-dasmoto/tree/master/Dasmotos%20Final
